install.packages("readxl")
install.packages("tidyverse")
install.packages('ggmap')
install.packages('purrr')
install.packages("tm")
library(readxl)
library(tidyverse)
library(ggmap)
library(purrr)
library(knitr)
library(ggplot2)
library(tm)

read <- readPDF(control = list(text = "-layout"))
document <- Corpus(URISource("2018_plans.pdf"), readerControl = list(reader = read))
doc <- content(document[[1]])
head(doc)